### PR TITLE
Loading view

### LINKED ISSUE #25: Informational Loading View Component
Create a view component to replace the `<Spinner />` that's currently in use in `ContextFeed`. The goal here is to create a loading animation (spinner?) that when you hover over it, will give details of what's going on.
For example:
- Incorrect DAO Address
- - Hovering over loader gives a pop up showing whatever error has occurred in the backend.
- GraphQL Error
... you get the idea

This view component would take in the `<Component.Logs>` data, check for errors or other information information, and present that.

### PR DESCRIPTION
**Pull request by shivgupt**
Closes #25

### CODE REVIEW

File: src/runtime/ContextFeed.tsx [hunk 1]
```diff
@@ -43,11 +43,7 @@ class ContextFeed extends React.Component<Props>
             </Consumer>
           )
         } else {
-          if (values.indexOf(undefined) > -1) {
```
Comment (dOrgJelli) [inline src/runtime/ContextFeed.tsx]: Let's leave this here, as the goal is to handle loading for the user of the library. We can add the ability to disable this if the user wants, but by default I think it's better to handle it for them.

Additional thought / want: we should support the user being able to override the loading component. This can be made into another task & PR.

File: src/runtime/ContextFeed.tsx [hunk 2]
```diff
@@ -2,7 +2,7 @@ import * as React from "react";
 
 // TODO: remove this dep from the package, and instead have the user
 //       of the library provide their own loading component
-const Spinner = require("react-spinkit");
+//const Spinner = require("react-spinkit");
```
Comment (dOrgJelli) [inline src/runtime/ContextFeed.tsx]: Let's just remove this + the comment above.

File: storybook/helpers/ComponentView.tsx [hunk 3]
```diff
@@ -55,26 +56,29 @@ export default class ComponentView extends React.Component<Props, State> {
...
-            </Typography>
-            {objectInspector(logs.react, `${name}.ReactLogs`, "React Logs")}
-            {objectInspector(logs.entity, `${name}.EntityLogs`, "Entity Logs")}
-            {objectInspector(logs.data, `${name}.DataLogs`, "Data Query Logs")}
-            {objectInspector(logs.code, `${name}.CodeLogs`, "Code Logs")}
-            {objectInspector(logs.prose, `${name}.ProseLogs`, "Prose Logs")}
-            </>
-          )}
+          {(entity: any, data: any, logs: ComponentLogs) => {
+            if ( !entity || !data)
```
Comment (dOrgJelli) [inline storybook/helpers/ComponentView.tsx]: My other comment says this, but let's not handle the loading here, as this is an example user view. Let's do it within the ContextFeed.

File: package.json [hunk 4]
```diff
@@ -16,10 +16,12 @@
   },
   "dependencies": {
     "@daostack/client": "0.1.4",
+    "lodash": "^4.17.11",
```
Comment (dOrgJelli) [inline package.json]: Ramda is already included as a dep, would you mind using that instead of lodash?

File: src/runtime/ContextFeed.tsx [hunk 5]
```diff
@@ -44,7 +44,14 @@ class ContextFeed extends React.Component<Props>
...
           if (values.indexOf(undefined) > -1) {
-            return <Spinner name='double-bounce' />
+            // Hacky way to find index of ComponentLogs in values
+            // TODO: find a better way to identify type of object
+            let i = _.findIndex(values, function(o: any) {
+              if (o && o["_react"])
+                  return true
+              return false
+            })
+            return <LoadingView logs={values[i]}/>
```
Comment (dOrgJelli) [inline src/runtime/ContextFeed.tsx]: need to check for valid `i` index here.

File: src/runtime/ContextFeed.tsx [hunk 6]
```diff
@@ -44,7 +44,14 @@ class ContextFeed extends React.Component<Props>
           )
         } else {
           if (values.indexOf(undefined) > -1) {
-            return <Spinner name='double-bounce' />
+            // Hacky way to find index of ComponentLogs in values
+            // TODO: find a better way to identify type of object
+            let i = _.findIndex(values, function(o: any) {
```
Comment (dOrgJelli) [inline src/runtime/ContextFeed.tsx]: So here it looks like you're searching for the [`_react`](https://github.com/dOrgTech/DAOcomponents/blob/d42f18d3c2d3b4414abb1e12e4dd15c7e3865acb/src/runtime/logging/ComponentLogs.ts#L61) member of the `ComponentLogs` class, but this won't work in all cases. Let me explain.

`values` in this function refers to the array of context consumers that're being consumed. For example in this case:
```html
<DAO.Data>
<Member.Data>
<Member.Logs>
{(dao, member, logs) => ( ... )}
...
```
`values` would contain [dao.data, member.data, member.logs], and the value of the index `i` would be `2`.

This breaks down however when `<Member.Logs>` is not present. For example:
```html
<DAO.Data>
<Member.Data>
{(dao, member) => ( ... )}
...
```
The value of the index `i` in your code would be -1.

So then what's the desired behavior and the solution to get to this?

In the case of the above code sample, if `<Member.Data>` is undefined, we want to show a spinner letting us know that the loading of the `Member` component is still in progress. In order to do this, we need to somehow know that the `Data` consumer is coming from `Member`, and then get the `Member.Logs` consumer... I'm thinking this requires a refactor of some sort. I'll look into this now and see if a solution pops up...

File: src/runtime/LoadingView.tsx [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+      if (value && value["_error"]) render.push(key)
+    })
+    return (
+      <Popup
+        trigger={<Spinner name='double-bounce'/>}
+        position="right center"
+        on="hover"
+      >
+        <>
+          {render.map(key => (objectInspector(logs[key], `${key}`, `${key} logs`)))}
```
Comment (dOrgJelli) [inline src/runtime/LoadingView.tsx]: It'd be great if instead of using the objectInspector, we had some conditional rendering that gave more information.

For now, we can just output the `Error.message`, and then improve it in a future PR.

Comment (dOrgJelli) [reply src/runtime/LoadingView.tsx]: But yah, let's remove object-inspector, as it's currently on a devDepdency and I don't want to add that to the final build (to try and keep things as slim as possible).

**Comment by dOrgJelli** [comment]
@shivgupt if you (1) check for invalid index `i` (2) replace lodash w/ ramda, and (3) remove the use of object-inspector, I'm good with merging this as is.

Once merged, we can have two parallel workstreams. One where I figure out a better way to solve the problem of `What component is having an issue loading a context feed?` (ex: deducing Member from Member.Data), and one where you either take on another task or add additional informative information to the diagnostics view.

File: package.json (hunk 4 above)
Comment (shivgupt) [reply package.json]: Opps I didn't realize Ramda was already included.

**Comment by shivgupt** [comment]
> @shivgupt if you (1) check for invalid index `i` (2) replace lodash w/ ramda, and (3) remove the use of object-inspector, I'm good with merging this as is.
> 
> Once merged, we can have two parallel workstreams. One where I figure out a better way to solve the problem of `What component is having an issue loading a context feed?` (ex: deducing Member from Member.Data), and one where you either take on another task or add additional informative information to the diagnostics view.

So

**Comment by shivgupt** [comment]
> @shivgupt if you (1) check for invalid index `i` (2) replace lodash w/ ramda, and (3) remove the use of object-inspector, I'm good with merging this as is.
> 
> Once merged, we can have two parallel workstreams. One where I figure out a better way to solve the problem of `What component is having an issue loading a context feed?` (ex: deducing Member from Member.Data), and one where you either take on another task or add additional informative information to the diagnostics view.

Updated with the requested changes 👍🏻
